// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/lorexzer0/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from foo.go:

func injectedMessage() string {
	string2 := provideMessage()
	return string2
}

// foo.go:

// foo.go:28
func main() {
	fmt.Println(injectedMessage())
}

// foo.go:33
// provideMessage provides a friendly user greeting.
func provideMessage() string {
	return "Hello, World!"
}
